spring:
  redis:
    database: 0
    host: 175.24.185.242
    port: 6379
    password: duanfa00Andfuck
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: 4ACkto:T+75l
    url: jdbc:p6spy:mysql://175.24.185.242:3306/medusa?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false